// Station name (normalised) -> TfL fare zone.
//
// This file is DATA. Regenerate it with full authoritative coverage by running:
//   node scripts/generate-zones.mjs        (needs network access to api.tfl.gov.uk)
// The checked-in copy below is the hand-curated core (Zones 1-3 in full, plus
// high-confidence outer hubs); the generator overlays TfL's complete StopPoint
// zone data on top of it. Boundary stations are stored at their inner zone.
export const ZONE_DATA = {
  "aldgate": 1,
  "aldgate east": 1,
  "angel": 1,
  "baker street": 1,
  "bank": 1,
  "barbican": 1,
  "bayswater": 1,
  "blackfriars": 1,
  "bond street": 1,
  "borough": 1,
  "cannon street": 1,
  "chancery lane": 1,
  "charing cross": 1,
  "covent garden": 1,
  "earls court": 1,
  "edgware road": 1,
  "elephant and castle": 1,
  "embankment": 1,
  "euston": 1,
  "euston square": 1,
  "farringdon": 1,
  "gloucester road": 1,
  "goodge street": 1,
  "great portland street": 1,
  "green park": 1,
  "holborn": 1,
  "hyde park corner": 1,
  "kings cross": 1,
  "kings cross st pancras": 1,
  "knightsbridge": 1,
  "lambeth north": 1,
  "lancaster gate": 1,
  "leicester square": 1,
  "liverpool street": 1,
  "london bridge": 1,
  "mansion house": 1,
  "marble arch": 1,
  "marylebone": 1,
  "monument": 1,
  "moorgate": 1,
  "mornington crescent": 1,
  "notting hill gate": 1,
  "old street": 1,
  "oxford circus": 1,
  "paddington": 1,
  "piccadilly circus": 1,
  "pimlico": 1,
  "queensway": 1,
  "regents park": 1,
  "russell square": 1,
  "shoreditch high street": 1,
  "sloane square": 1,
  "south kensington": 1,
  "southwark": 1,
  "st jamess park": 1,
  "st pauls": 1,
  "temple": 1,
  "tottenham court road": 1,
  "tower gateway": 1,
  "tower hill": 1,
  "vauxhall": 1,
  "victoria": 1,
  "warren street": 1,
  "waterloo": 1,
  "westminster": 1,
  "all saints": 2,
  "barons court": 2,
  "bethnal green": 2,
  "blackwall": 2,
  "bow church": 2,
  "bow road": 2,
  "brixton": 2,
  "brondesbury": 2,
  "brondesbury park": 2,
  "caledonian road": 2,
  "camden town": 2,
  "canada water": 2,
  "canary wharf": 2,
  "clapham common": 2,
  "clapham high street": 2,
  "clapham north": 2,
  "crossharbour": 2,
  "cutty sark": 2,
  "dalston junction": 2,
  "dalston kingsland": 2,
  "denmark hill": 2,
  "deptford bridge": 2,
  "devons road": 2,
  "elverson road": 2,
  "finchley road": 2,
  "finchley road and frognal": 2,
  "finsbury park": 2,
  "fulham broadway": 2,
  "goldhawk road": 2,
  "gospel oak": 2,
  "greenwich": 2,
  "hackney central": 2,
  "hackney downs": 2,
  "hackney wick": 2,
  "haggerston": 2,
  "hammersmith": 2,
  "hampstead": 2,
  "heron quays": 2,
  "highbury and islington": 2,
  "homerton": 2,
  "hoxton": 2,
  "imperial wharf": 2,
  "island gardens": 2,
  "kennington": 2,
  "kensington olympia": 2,
  "kentish town": 2,
  "kentish town west": 2,
  "kilburn": 2,
  "kilburn park": 2,
  "ladbroke grove": 2,
  "langdon park": 2,
  "latimer road": 2,
  "limehouse": 2,
  "maida vale": 2,
  "manor house": 2,
  "mile end": 2,
  "mudchute": 2,
  "new cross": 2,
  "new cross gate": 2,
  "nunhead": 2,
  "oval": 2,
  "parsons green": 2,
  "peckham rye": 2,
  "poplar": 2,
  "pudding mill lane": 2,
  "putney bridge": 2,
  "queens park": 2,
  "queens road peckham": 2,
  "ravenscourt park": 2,
  "rotherhithe": 2,
  "royal oak": 2,
  "shadwell": 2,
  "shepherds bush": 2,
  "shepherds bush market": 2,
  "south hampstead": 2,
  "south quay": 2,
  "st johns wood": 2,
  "stamford brook": 2,
  "star lane": 2,
  "stepney green": 2,
  "stockwell": 2,
  "surrey quays": 2,
  "swiss cottage": 2,
  "turnham green": 2,
  "upper holloway": 2,
  "wandsworth road": 2,
  "wapping": 2,
  "west brompton": 2,
  "west hampstead": 2,
  "west india quay": 2,
  "west kensington": 2,
  "westbourne park": 2,
  "westferry": 2,
  "white city": 2,
  "willesden junction": 2,
  "abbey road": 3,
  "acton town": 3,
  "alexandra palace": 3,
  "archway": 3,
  "balham": 3,
  "blackhorse road": 3,
  "bounds green": 3,
  "brent cross": 3,
  "brockley": 3,
  "bromley by bow": 3,
  "canning town": 3,
  "catford": 3,
  "chiswick park": 3,
  "clapham south": 3,
  "colliers wood": 3,
  "crystal palace": 3,
  "custom house": 3,
  "dollis hill": 3,
  "ealing broadway": 3,
  "ealing common": 3,
  "east acton": 3,
  "east finchley": 3,
  "forest hill": 3,
  "golders green": 3,
  "gunnersbury": 3,
  "hanger lane": 3,
  "harlesden": 3,
  "highgate": 3,
  "hither green": 3,
  "honor oak park": 3,
  "kew gardens": 3,
  "lee": 3,
  "lewisham": 3,
  "leyton": 3,
  "leytonstone": 3,
  "london city airport": 3,
  "neasden": 3,
  "north acton": 3,
  "northfields": 3,
  "plaistow": 3,
  "pontoon dock": 3,
  "prince regent": 3,
  "royal victoria": 3,
  "seven sisters": 3,
  "south ealing": 3,
  "south wimbledon": 3,
  "stonebridge park": 3,
  "stratford": 3,
  "stratford international": 3,
  "sydenham": 3,
  "tooting bec": 3,
  "tooting broadway": 3,
  "tottenham hale": 3,
  "tufnell park": 3,
  "turnpike lane": 3,
  "upton park": 3,
  "walthamstow central": 3,
  "west ham": 3,
  "west silvertown": 3,
  "willesden green": 3,
  "wood green": 3,
  "abbey wood": 4,
  "barking": 4,
  "morden": 4,
  "richmond": 4,
  "wembley park": 4,
  "woolwich": 4,
  "woolwich arsenal": 4,
  "cockfosters": 5,
  "edgware": 5,
  "high barnet": 5,
  "hounslow central": 5,
  "hounslow east": 5,
  "hounslow west": 5,
  "stanmore": 5,
  "epping": 6,
  "hatton cross": 6,
  "heathrow terminal 4": 6,
  "heathrow terminal 5": 6,
  "heathrow terminals 2 3": 6,
  "upminster": 6,
  "uxbridge": 6,
};
