// Generate lib/zones-data.js (station name -> TfL fare zone) from the TfL
// Unified API. Run wherever api.tfl.gov.uk is reachable:
//
//   node scripts/generate-zones.mjs
//   TFL_APP_KEY=xxxx node scripts/generate-zones.mjs   # higher rate limits
//
// It pulls every zonal station across the rail-like modes, normalises names the
// same way the app does, overlays them on the existing curated table (TfL wins),
// and rewrites lib/zones-data.js. Stations without a numeric TfL zone are skipped
// (the app falls back to a distance estimate for those).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { normStation } from "../lib/zones.js";
import { ZONE_DATA as CURATED } from "../lib/zones-data.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dir, "../lib/zones-data.js");
const BASE = "https://api.tfl.gov.uk";
const KEY = process.env.TFL_APP_KEY || "";
const MODES = ["tube", "dlr", "overground", "elizabeth-line", "tram", "national-rail"];

const withKey = (u) => (KEY ? u + (u.includes("?") ? "&" : "?") + "app_key=" + KEY : u);

async function getJSON(path) {
  const res = await fetch(withKey(BASE + path), { headers: { Accept: "application/json" } });
  if (!res.ok) throw new Error(`TfL ${res.status} on ${path}`);
  return res.json();
}

// "1" -> 1, "1+2" -> 1 (inner), "Special"/"" -> null.
function parseZone(v) {
  const m = /\d+/.exec(String(v ?? ""));
  return m ? Number(m[0]) : null;
}

function zoneOf(sp) {
  const props = sp.additionalProperties || [];
  const p = props.find((x) => (x.key || "").toLowerCase() === "zone");
  return p ? parseZone(p.value) : null;
}

async function collectMode(mode) {
  const out = [];
  let page = 1;
  for (;;) {
    const data = await getJSON(`/StopPoint/Mode/${mode}?page=${page}`);
    const sps = data.stopPoints || [];
    if (!sps.length) break;
    out.push(...sps);
    const total = data.total || 0;
    if (out.length >= total || sps.length < (data.pageSize || sps.length)) break;
    page++;
  }
  return out;
}

const zones = { ...CURATED }; // start from the curated base; TfL overrides below
let added = 0, updated = 0;

for (const mode of MODES) {
  process.stdout.write(`Fetching ${mode}… `);
  let sps = [];
  try {
    sps = await collectMode(mode);
  } catch (e) {
    console.log(`failed (${e.message}) — skipping`);
    continue;
  }
  let n = 0;
  for (const sp of sps) {
    const z = zoneOf(sp);
    const name = normStation(sp.commonName);
    if (!z || !name) continue;
    // Keep the lower zone if a station appears under multiple modes.
    if (zones[name] == null) { zones[name] = z; added++; n++; }
    else if (z < zones[name]) { zones[name] = z; updated++; n++; }
  }
  console.log(`${sps.length} stops, ${n} zoned`);
}

const entries = Object.entries(zones).sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]));
const body = entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`).join("\n");
const header = `// Station name (normalised) -> TfL fare zone.
//
// GENERATED by scripts/generate-zones.mjs on ${new Date().toISOString().slice(0, 10)}
// from TfL StopPoint data (${entries.length} stations). Re-run that script to refresh.
// Boundary stations are stored at their inner zone.`;
writeFileSync(OUT, `${header}\nexport const ZONE_DATA = {\n${body}\n};\n`);
console.log(`\nWrote ${OUT}: ${entries.length} stations (+${added} new, ${updated} corrected).`);
